### ISSUE TITLE
SmoothWAN in Hyper-V: Only 1 WAN is working

### ISSUE THREAD

**Issue by ccmks** [SmoothWAN/SmoothWAN#103]
![1WAN](https://user-images.githubusercontent.com/49300986/218957261-faff5d19-38ef-48f5-9a5d-2ab442d6559f.PNG)
Hello,

I do noticed that only 1 WAN that is working at a time, instead of 3 of them.

How can I make all of them active? All of them have internet connection, but won't show as active in speedify

Thank you

**Comment by TalalMash** [comment]
Im guessing this is hyper v from the other issue? 
Can you post the configuration?

**Comment by ccmks** [comment]
How can I get the configuration?

**Comment by TalalMash** [comment]
Hyper-V settings , network virtual switch manager screenshot, disable protected networking, hardware topology, post your `/etc/config/network/` and `ip route` results here.

**Comment by ccmks** [comment]
Here is the IP route
0.0.0.0/1 dev connectify0 scope link
default via 10.50.53.1 dev eth3 proto static metric 10
10.50.52.0/24 dev eth2 proto static scope link metric 10
10.50.53.0/24 dev eth3 proto static scope link metric 10
10.202.0.0/24 dev connectify0 proto kernel scope link src 10.202.0.2
123.123.123.123 via 10.50.53.1 dev eth3
128.0.0.0/1 dev connectify0 scope link
172.17.17.0/24 dev br-lan proto kernel scope link src 172.17.17.2
192.168.123.0/24 dev eth1 proto static scope link metric 10


Here is the /etc/config/network

config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd06:cdd8:611c::/48'

config device
        option name 'br-lan'
        option type 'bridge'
        list ports 'eth0'

config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option ipaddr '172.17.17.2'

config interface 'wan'
        option device 'eth1'
        option proto 'dhcp'

config interface 'wan6'
        option device 'eth1'
        option proto 'dhcpv6'

config interface 'AutoUSBeth1'
        option device 'eth1'
        option proto 'static'
        option ipaddr '192.168.123.29'
        option netmask '255.255.255.0'
        option gateway '192.168.123.1'
        option metric '10'

config interface 'AutoUSBeth2'
        option device 'eth2'
        option proto 'static'
        option netmask '255.255.255.0'
        option gateway '10.50.52.1'
        option ipaddr '10.50.52.129'
        option metric '10'

config interface 'AutoUSBeth3'
        option device 'eth3'
        option proto 'static'
        option netmask '255.255.255.0'
        option gateway '10.50.53.1'
        option ipaddr '10.50.53.129'
        option metric '10'

config interface 'AutoUSB0'
        option proto 'dhcp'
        option device 'usb0'
        option metric '40'

config interface 'AutoUSB1'
        option proto 'dhcp'
        option device 'usb1'
        option metric '41'

config interface 'AutoUSB2'
        option proto 'dhcp'
        option device 'usb2'
        option metric '42'

config interface 'AutoUSB3'
        option proto 'dhcp'
        option device 'usb3'
        option metric '43'

config interface 'Speedify'
        option proto 'none'
        option device 'connectify0'

config device
        option name 'eth2'

**Comment by TalalMash** [comment]
Ah, you should set the metric to be different for each WAN, then the `ip route` command should show multiple `default` entries (as per WAN). The note in LuCI configuration page is dedicated to Wireless setup, not generally. (e.g 10 metric for each WAN)

**Comment by ccmks** [comment]
![image](https://user-images.githubusercontent.com/49300986/219204240-6afc95a3-7e69-46f5-b007-7794a9c60ef1.png)
I am following the instruction note here, therefore all WAN will have same metric

**Comment by ccmks** [comment]
I have followed your instruction above and I am getting only WAN1 and WAN3 connected, the WAN2 is not working

![image](https://user-images.githubusercontent.com/49300986/219205671-b1bfcabd-3d04-4c3b-a6d9-37728b545a57.png)

IP route

0.0.0.0/1 dev connectify0 scope link
default via 192.168.123.1 dev eth1 proto static metric 11
default via 10.50.52.1 dev eth2 proto static metric 12
default via 10.50.53.1 dev eth3 proto static metric 13
10.50.52.0/24 dev eth2 proto static scope link metric 12
10.50.53.0/24 dev eth3 proto static scope link metric 13
10.202.0.0/24 dev connectify0 proto kernel scope link src 10.202.0.2
123.123.123.123 via 192.168.123.1 dev eth1
128.0.0.0/1 dev connectify0 scope link
172.17.17.0/24 dev br-lan proto kernel scope link src 172.17.17.2
192.168.123.0/24 dev eth1 proto static scope link metric 11

/etc/config/network
config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd06:cdd8:611c::/48'

config device
        option name 'br-lan'
        option type 'bridge'
        list ports 'eth0'

config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option ipaddr '172.17.17.2'

config interface 'wan'
        option device 'eth1'
        option proto 'dhcp'

config interface 'wan6'
        option device 'eth1'
        option proto 'dhcpv6'

config interface 'AutoUSBeth1'
        option device 'eth1'
        option proto 'static'
        option ipaddr '192.168.123.29'
        option netmask '255.255.255.0'
        option gateway '192.168.123.1'
        option broadcast '192.168.123.255'
        option metric '11'

config interface 'AutoUSBeth2'
        option device 'eth2'
        option proto 'static'
        option netmask '255.255.255.0'
        option gateway '10.50.52.1'
        option ipaddr '10.50.52.129'
        option broadcast '10.50.52.255'
        option metric '12'

config interface 'AutoUSBeth3'
        option device 'eth3'
        option proto 'static'
        option netmask '255.255.255.0'
        option gateway '10.50.53.1'
        option ipaddr '10.50.53.129'
        option broadcast '10.50.53.255'
        option metric '13'

config interface 'AutoUSB0'
        option proto 'dhcp'
        option device 'usb0'
        option metric '40'

config interface 'AutoUSB1'
        option proto 'dhcp'
        option device 'usb1'
        option metric '41'

config interface 'AutoUSB2'
        option proto 'dhcp'
        option device 'usb2'
        option metric '42'

config interface 'AutoUSB3'
        option proto 'dhcp'
        option device 'usb3'
        option metric '43'

config interface 'Speedify'
        option proto 'none'
        option device 'connectify0'

config device
        option name 'eth2'

**Comment by TalalMash** [comment]
in terminal `ping 10.50.52.1` to see if it's a connectivity issue

**Comment by ccmks** [comment]
I can ping to it, not problem

![image](https://user-images.githubusercontent.com/49300986/219207590-02fc2dbf-e2bb-4bf0-8d52-fcb09f3ff0f1.png)

**Comment by TalalMash** [comment]
do `ping -I eth2 1.1.1.1`

**Comment by ccmks** [comment]
I tried and no response. I just confirmed that WAN2 doesn't have active internet connection.

I will fix it.

Thank you for your support and great project!

**Comment by TalalMash** [comment]
Great! will add the broadcast note in Wiki soon for static IP setups.
Feel free to reopen if more issues persist.
