### ISSUE TITLE
Firefox 108+: Speedify installed, but stuck on Restart Speedify button.

### ISSUE THREAD

**Issue by Sealilly76** [SmoothWAN/SmoothWAN#123]
Hey all, installing on Slate, all went smooth until I installed Speedify. Log says installed succesfully but at Status:Overview, I only have the blue Restart Speedify button. No joy after clicking. Uninstalled successfully, reinstalled, rebooted, still no joy. Any ideas? 

![Capture](https://user-images.githubusercontent.com/126890123/222747580-eb343849-1ecf-4ef3-949d-451cc21f04ad.JPG)

**Comment by Sealilly76** [comment]
Seemed to be a Firefox issue, worked fine with Chrome.

**Comment by TalalMash** [comment]
Thanks for the report, were there any extensions e.g adblock?

**Comment by TalalMash** [comment]
Same issue here with FF, happens with other WebUI too like Ubiquity, add exception to websocket:
![image](https://user-images.githubusercontent.com/96490382/222788678-016b520d-4e0b-4819-a3b2-e23918556ba7.png)

**Comment by TalalMash** [comment]
Also needed for web terminal with port `7681`

**Comment by TalalMash** [comment]
Next version (v1) will have http by default, https still available.

**Comment by Sealilly76** [comment]
Thank you, that worked! This setup is AWESOME.

**Comment by TalalMash** [comment]
Fixed in `0.99.9HF4` , clear browser history related to `172.17.17.2` and cache. 
Visit with `http` instead of `https`
