### ISSUE TITLE
Support for Banana Pi R64

### ISSUE THREAD

**Issue by TalalMash** [SmoothWAN/SmoothWAN#126]
**Status**: Basic support image release, needs testers.

**Comment by bencorrado** [comment]
I have a few of these sitting in a box. Would you like one for your tests?

**Comment by TalalMash** [comment]
> I have a few of these sitting in a box. Would you like one for your tests? Send me your address if so.

Thanks, will let you know on next update.

**Comment by TalalMash** [comment]
Reopening when I can locally test it.
