### ISSUE TITLE
Support for BananaPi R3

### ISSUE THREAD

**Issue by TalalMash** [SmoothWAN/SmoothWAN#127]
**Status**: Basic support image release, needs testers.

**Comment by kputland** [comment]
Where do you think this fits performance wise with the Slate AX and the NanoPi R6S? I like the idea of the eight antennas. And price wise it's in the same ballpark if you don't include the 2.5G SFPs.

**Comment by TalalMash** [comment]
It should be slightly slower than the R6S.

**Comment by TalalMash** [comment]
This got released too: https://www.cnx-software.com/2023/03/14/banana-pi-bpi-r3-mini-low-profile-2-5gbe-router-board-mediatek-filogic-830-soc/

**Comment by kputland** [comment]
Should have a RPI-R3 on Monday

**Comment by kputland** [comment]
Boots from image `SmoothWAN-0.99.9HF5-BananaPi-R3-SDcard.img.gz` , but it's on 192.168.1.1 and I don't see any customizations. no webUI. SSH fingerprint changes on reboot. Will try a vanila OpenWRT

**Comment by kputland** [comment]
Will have to come back to this device in about a month. I won't have much time until mid June.

**Comment by TalalMash** [comment]
Seems to be booting from NAND/NOR that is shipped with the device, not SDcard. Or you may have to install using: https://forum.banana-pi.org/t/banana-pi-bpi-r3-openwrt-image/13236/82

**Comment by kputland** [comment]
Checked jumpers. changed images.
When I flash the official image
`openwrt-mediatek-filogic-bananapi_bpi-r3-sdcard.img.gz`
banner repors ` OpenWrt SNAPSHOT, r22884-22ff416483`

When I flash `SmoothWAN-0.99.9HF5-BananaPi-R3-SDcard.img.gz`
banner reports ` OpenWrt SNAPSHOT, r22480-18d516a649`

which leads me to believe that it is booting from the SD card.

There is a very quick menu in the serial console at boot
<img width="848" alt="image" src="https://github.com/SmoothWAN/SmoothWAN/assets/1480163/8763099d-254f-4b60-82b2-b39e153eb8b9">

The only option that works is `1. Run default boot command` or `4. Boot recovery system from SD card.`

**Comment by TalalMash** [comment]
Reopening when I can locally test it.
