### ISSUE TITLE
WebUI not showing/allowing login to Speedify

### ISSUE THREAD

**Issue by jmdurant** [SmoothWAN/SmoothWAN#132]
Hey, running 0.99.9HF4 with a new install. Speedify downloads and installs, but when I go to overview and input my username and password the WebUI does not redirect and still shows the need to login.  Looking in the logs it appears to be connected, but the WebUI is not redirecting and acknowledging that I'm logged in.  Username and password confirmed correct with speedify.  RPI4 build.

**Comment by TalalMash** [comment]
Hi, is this with a free account?

**Comment by jmdurant** [comment]
Hey! It is, with 2tb free per month. Apologies if it doesn’t work with that
and missed that.  Thanks for the hard work on this project.

**Comment by TalalMash** [comment]
No problem, added a note in releases.
