### ISSUE TITLE
v0.99.9 HF4 - FLINT - DHCP ISSUE

### ISSUE THREAD

**Issue by chansearrington** [SmoothWAN/SmoothWAN#136]
Hey @TalalMash,

I've flashed SmoothWAN v0.99.9 HF4 on my GL.iNET Flint device and I think I'm running into an issue (sorry, I'm no expert, but if you tell me what to check I can look into it)

I think (not sure) that the Flint version is missing the DHCP / DNS capabilities.

There are no devices listed in the Active DCHP leases.
<img width="1064" alt="CleanShot 2023-03-15 at 02 26 45@2x" src="https://user-images.githubusercontent.com/123082/225238327-9edf8c0d-1e73-40d5-8337-0637db27c2c2.png">

If I go to Network > DCHP and DNS... the screen seems to show that I don't have dnsmasq install.

<img width="999" alt="CleanShot 2023-03-15 at 02 35 05@2x" src="https://user-images.githubusercontent.com/123082/225238632-931c95af-35f9-4ff7-ab2e-98bbf245a405.png">

If I change the main address network address from 172.17.17.2 to something like 192.168.1.1 then the router doesn't even hand out any kind of DCHP and tries to pass the external modem address directly through... which doesn't work. The only way for me to access the router is to manually define the router / ipaddress / subnet

Here's some other screenshots in case they help too.
<img width="1840" alt="CleanShot 2023-03-15 at 02 07 57@2x" src="https://user-images.githubusercontent.com/123082/225241321-ae38984f-5e14-4e36-a94c-6a3365d3574d.png">

**Comment by chansearrington** [comment]
If I revert all the way back to [SmoothWAN-0.99.8HF1-TEST.3-GLiNet-Flint-WebUI.img.tar](https://github.com/SmoothWAN/SmoothWAN/releases/download/0.99.8-flint-test%232/SmoothWAN-0.99.8HF1-TEST.3-GLiNet-Flint-WebUI.img.tar)

then the problem goes away.

But I have to go all the way back to 0.99.8

the problem persists in all the 99.9 releases. I checked them each individually.

**Comment by bt61** [comment]
Not sure about Flint, but for RPi all the DNS and DHCP got moved to AdGuard Home, check there (under Services).

**Comment by TalalMash** [comment]
Correct, added the notice in the main page too (it was hidden in changelog).
Simply change the IP of LAN and the range/address in AdGuard Home.

[(if you need dnsmasq back for other reasons)](https://smoothwan.com/adg/#due-to-popular-request-and-leak-proof-dns-adgh-is-the-default-dhcp-server)

**Comment by chansearrington** [comment]
Got it and that worked. Thanks!

I don't think I needed / wanted dnsmask. there just wasn't anything in the UI telling me where to edit the DHCP range or that dnsmask was replaced with AdGuard.

**Comment by TalalMash** [comment]
Reverted to stock openwrt dhcp configuration and dnsmasq but with working adguardhome client statistics.
Fixed in 0.99.5HF5
