### ISSUE TITLE
Install Smoothwan from USB dongle to internal drive

### ISSUE THREAD

**Issue by zbynekdrlik** [SmoothWAN/SmoothWAN#152]
Hi, is it possible to move smoothwan from usb dongle to internal drive as I am missing that one usb port on laptop used for smoothwan?

**Comment by TalalMash** [comment]
Adding a LuCI app for this next release. Yes it's possible by simply using `dd` in terminal to clone the dongle to internal, even on a live system.
All data is lost on the internal drive, unless you partition the drive.

**Comment by zbynekdrlik** [comment]
So many promises for next release :) Is there some planed date of release @TalalMash ?

**Comment by TalalMash** [comment]
UI option seems risky for users testing out, here's how to copy from flash drive to your internal drive:
Warning: All internal disk data will be lost.

1. Enter `lsblk` in Services -> Terminal after logging in to view connected disks.
2. Note down the internal drive path, e.g `/dev/sda` for internal.
3. Download the image straight to the drive, e.g for PC with 0.99.5.HF5:
```
curl -L https://github.com/SmoothWAN/SmoothWAN/releases/download/0.99.9HF5/SmoothWAN-0.99.9HF5-PC-EFI-AMD64-DiskImage-or-WebUI.img.gz | gzip -d -c | dd bs=4M of=/dev/sda conv=fsync
```
