### ISSUE TITLE
no display on oled shown after upgrade / install v0.99.9HF5

### ISSUE THREAD

**Issue by lkimloong** [SmoothWAN/SmoothWAN#164]
Hi,

Wish to check after install or upgrade to the latest version, my oled is not displaying any information. Is there any setting need to tweak?

**Comment by TalalMash** [comment]
OLED support was deprecated since 0.99.8 , new Speedify version is incompatible. This will change next release.

**Comment by TalalMash** [comment]
VT100 256x128 TUI console will be provided for DIYers to adapt, OLED is dropped due to longevity issues.
