### ISSUE TITLE
Engarde install on other VPS

### ISSUE THREAD

**Issue by ccmks** [SmoothWAN/SmoothWAN#171]
Hello,

I saw your documentation that in order to install Engarde, you were using Vultr as the example. However, I have different VPS provider I want to use, do you have instruction to setup on other VPS provider? Especially the unmanaged VPS

Thank you

**Comment by TalalMash** [comment]
Hi,
You have to be familiar with command line if cloud-init is not supported by your provider, some providers may require extra configuration or settings.
Adding one liner script next release under advanced section.

**Comment by TalalMash** [comment]
AWS and Oracle examples:
https://smoothwan.discourse.group/t/smoothwan-engarde-on-oracle-cloud
