### ISSUE TITLE
Support for Dual-Q H721

### ISSUE THREAD

**Issue by mailz23** [SmoothWAN/SmoothWAN#74]
Is there any way you can compile a build for the Dual-Q H721 router? It is a dual LTE modem router. it is located in MIPS-MT7621-DUAL_Q

**Comment by TalalMash** [comment]
There are no MIPS builds for Speedify as of today, but I've heard from their livestreams that there may be soon.

**Comment by mailz23** [comment]
> There are no MIPS builds for Speedify as of today, but I've heard from their livestreams that there may be soon.

Thank you for the update. Hopefully soon. The firmware is amazing. Thank you for all the hard work.
