### ISSUE TITLE
ISP DNS can leak with default setup

### ISSUE THREAD

**Issue by DalSoft** [SmoothWAN/SmoothWAN#77]
I think it would be a good idea to add to the documentation for users to do a [dnsleaktest](https://www.dnsleaktest.com). This is because people will plug in various ISP configed / locked down devices. For example I plugged in a router / modem from British Telecom that is locked down so I can't change the dns settings or put it in bridge mode. My dns leaked to the ISP dns server 😱

It's a simple fix by changing the "Use DNS servers advertised by peer setting" on the WAN interfaces.

Note: some streaming services e.g. Amazon are using DNS leaks to detect VPN's.

**Comment by TalalMash** [comment]
Using DNS forwarding next release, for older version users example:
![image](https://user-images.githubusercontent.com/96490382/211365099-cf4abc36-0728-465d-93fe-25185d2f083b.png)
![image](https://user-images.githubusercontent.com/96490382/211365173-d16d3a50-8ac6-41e7-84b9-63af0739746a.png)

Next version will forward to inactive ADGhome by default.

**Comment by TalalMash** [comment]
Fixed in latest release. (no resolvconf)
