### ISSUE TITLE
Support for NETGEAR R7800 - Nighthawk X4S AC2600 - Netgear XR500

### ISSUE THREAD

**Issue by TalalMash** [SmoothWAN/SmoothWAN#94]
**Status:** In development
Will be released in v0.99.9
All models are mostly identical.

Need testers.

**Comment by benbeckner** [comment]
Good morning!
Can you provide details on what changes are in this version and what you need tested?

Thanks!

**Comment by TalalMash** [comment]
@benbeckner lots of changes! releasing the image soon with the changelogs.
Port order and configuration, will post the instructions here, thanks.
Supporting Netgear over Belkin since they're difficult to brick (even intentionally) and no restrictions to 3rd party firmware.

**Comment by TalalMash** [comment]
Unfortunately these appear to be mostly out of stock and chip is old and overpriced in the new lineup, sorry for the noise! Replacing with the recent WAX series which will be pushed to official OpenWRT soon!
