### ISSUE TITLE
GPIO on Raspberry Pi 4

### ISSUE THREAD

**Issue by BigWillOKC** [SmoothWAN/SmoothWAN#99]
Hello, I'm coming over from OpenMPTCProuter and would like to enable the same functionality I have on my Pi with that setup.  I have a momentary switch connected to my Pi on GPIO 3 (pins 5 and 6) that allows me to shutdown and restart the Pi with a button press.  When running SmoothWAN, it will boot the Pi if its already shutdown, but it will not execute the shutdown when I press the button.  Is there something I need to do differently?  I'm using the following entry in my config.txt

# Power Button Shutdown/Startup
dtoverlay=gpio-shutdown
# Power Button Status LED
gpio=15=op,dh

**Comment by TalalMash** [comment]
Hello!
Don't have the Pi anymore (hit by ⚡), the `kmod-gpio-button-hotplug` is missing by default, is that installed?

**Comment by BigWillOKC** [comment]
That was it, thank you so much!  Any idea when PnP mini display monitor support will be added?

**Comment by TalalMash** [comment]
Great will add it next release, regarding the display: it's already supported in version 0.99.8, but the choice of display will change in v1 due to the SSD1306 having short lifespan.

**Comment by TalalMash** [comment]
Speedify UI fullscreen link is unauthenticated, you can use a spare (old) phone as an alternative.
M5 stack may be the default in v1 with USB & MQTT-over-network support.

**Comment by BigWillOKC** [comment]
That's a good idea.  I'm building a mobile internet system in a small Pelican style case, so i would love to be able to see that speedify ui really easily or at least the stats.  It would be ideal if i could have it show on the 5" screen i have installed for the Pi, but guessing that's a no go.

**Comment by TalalMash** [comment]
Adding a TUI is possible for plug and play devices, if the 5 inch display is using HDMI and OpenWRT console is visible then it's feasible to implement, this will also benefit x86/mini-pc, this is definitly in plan.

**Comment by TalalMash** [comment]
Opening a new issue regarding the display on any update.
